import Link from "next/link";

const steps = [
  ["01", "Seed a new problem", "The previous block hash deterministically generates a TSP instance. Every miner gets the same fresh routing problem, and no one can solve it far in advance."],
  ["02", "Search like a colony", "Each miner uses Ant Colony Optimization to construct tours. Good edges gain pheromone; evaporating pheromone prevents the search from freezing around an early guess."],
  ["03", "Keep the hash lottery", "A valid tour clears the quality gate. Its improvement makes the miner's hash target easier by a bounded amount, but a conventional hash still decides who earns the block."],
  ["04", "Measure the cost", "The simulator repeats this for SHA-PoW, pure optimization, and several hybrid λ values, then compares fork rate, reward inequality, strategic advantage, and useful work per energy proxy."],
];

export default function HowItWorks() {
  return <main>
    <header className="masthead"><div className="brand"><span className="ant-mark" aria-hidden="true">⌁</span><div><p>AntChain / C++ research simulator</p><h1>Mechanism guide</h1></div></div><div className="mast-actions"><nav aria-label="Primary navigation"><Link href="/">Workbench</Link><Link href="/how-it-works" aria-current="page">How it works</Link><Link href="/network">Live network</Link></nav><span className="status"><i /> Local execution</span></div></header>
    <section className="guide-hero"><p className="kicker">A hybrid, not a replacement</p><h2>Let optimization help the lottery—without letting it decide consensus.</h2><p>AntChain tests a narrow proposition: can a chain obtain useful routing solutions while retaining the memoryless hash lottery that makes proof-of-work predictable and resistant to private algorithmic advantages?</p></section>
    <section className="flow" aria-label="AntChain mechanism flow">{steps.map(([number, title, text], index) => <article className="flow-step" key={number}><div className="step-no">{number}</div><div><h2>{title}</h2><p>{text}</p></div>{index < steps.length - 1 && <span className="flow-line" aria-hidden="true">→</span>}</article>)}</section>
    <section className="equation-panel"><div><p className="kicker">The bounded advantage</p><h2>Quality shifts the target; it never grants the block outright.</h2><p>For a reference tour length <i>f</i><sub>old</sub> and a miner&apos;s candidate <i>f</i>(<i>x</i>), the target becomes:</p></div><div className="formula">T(<i>x</i>) = T<sub>0</sub> · [1 + λ · (<i>f</i><sub>old</sub> − <i>f</i>(<i>x</i>)) / <i>f</i><sub>old</sub>]</div><p className="formula-note">λ controls the maximum reward for better optimization. A lower tour length can improve a miner&apos;s odds, but the final success remains a fresh SHA-style hash trial.</p></section>
    <section className="comparison"><p className="kicker">Why the three-way experiment?</p><h2>Each baseline isolates a different claim.</h2><div className="comparison-grid"><article><span>SHA-PoW</span><h3>Security baseline</h3><p>No optimization component. Its work-proportional lottery sets the control for fork rate and reward fairness.</p></article><article><span>Pure PoAO</span><h3>Failure baseline</h3><p>The first sufficiently good solution wins. This exposes the private knowledge and pheromone-memory advantages that a hash lottery avoids.</p></article><article><span>Hybrid</span><h3>Research subject</h3><p>Optimization gates and reweights hashing. The key question is how much useful work it extracts before fairness or stability degrades.</p></article></div></section>
    <section className="warning"><p className="kicker">The important finding</p><h2>The quality gate can itself be unfair at scale.</h2><p>At 200 miners with a heavy-tailed hashrate distribution, smaller miners often failed to obtain enough ACO iterations to clear the eligibility gate. They were excluded before the hash lottery began—an open mechanism-design problem that λ tuning alone cannot solve.</p><Link className="guide-cta" href="/">Run the comparison in the workbench →</Link></section>
  </main>;
}
